[add] setting page
lit-kansai/dj-system-admin pull request #23
Opened 2022-11-15 07:13 UTC by kuro48

設定画面のUI実装しました

2022-11-16 02:01 UTC, txxxxc requested changes
実装ありがとう！全体的に良さそうです！！
何個か改善点挙げたので、修正お願いします！

2022-11-16 02:01 UTC, txxxxc commented on src/pages/setting.vue
> +    margin-top: 130px;
masterの方にサイドバーが実装されていて、`git pull origin master`すると反映されると思うので、反映してもらってからレイアウト調整してもらえると🙏

2022-11-16 09:55 UTC, kuro48 commented on src/pages/setting.vue
> +    margin-top: 130px;
`git-origin-master`したんですけど、反映されないんですよね、、、

2022-11-16 12:30 UTC, kuro48 commented on src/pages/setting.vue
> +    margin-top: 130px;
すみません！解決しました！

2022-11-16 12:32 UTC, kuro48 commented on src/pages/setting.vue
> +        color="#1867C0"
Vuetifyで用意されてる`blue`とFigmaの方の青が若干違うんですけどどうすればいいですか？（Vuetifyの方が若干薄いです）

2022-11-16 13:14 UTC, txxxxc commented on src/pages/setting.vue
> +        color="#1867C0"
個人的には耐えれる範囲かなって思ってるんやけど、一旦がしだに聞くわ

2022-11-16 13:35 UTC, txxxxc commented on src/pages/setting.vue
> +        color="#1867C0"
@kuro48 
がしだに確認取れました！変えちゃってOKです！

2022-11-16 14:39 UTC, kuro48 commented
改めて確認お願いします！！

2022-11-16 16:15 UTC, txxxxc reviewed
めっちゃ良くなってる！！！
あと一個だけお願いします！🙏

2022-11-16 16:24 UTC, kuro48 commented on src/pages/login.vue
> +    <v-btn id="login-button" color="blue" class="d-inline-flex mt-5 text-none">
この記事、vuetify2のカラーでvuetify3だと適用されないみたいなんですよ、、

2022-11-16 16:26 UTC, kuro48 commented on src/pages/login.vue
> +    <v-btn id="login-button" color="blue" class="d-inline-flex mt-5 text-none">
まだ、そこまで用意されてないんですよね、、

2022-11-17 00:06 UTC, txxxxc commented on src/pages/login.vue
> +    <v-btn id="login-button" color="blue" class="d-inline-flex mt-5 text-none">
`color="blue-darken-2"`にすると適用されるっぽいから試してもらえると嬉しい🙇‍♂️
![image](https://user-images.githubusercontent.com/22112440/202321867-4b96934b-6b3e-4aed-8e7e-ffbaa6f36f6a.png)

2022-11-17 00:07 UTC, txxxxc commented
あ、あとファイル名を`setting.vue`から`settings.vue`に変更お願いしたい！！！

2022-11-17 01:38 UTC, kuro48 commented on src/pages/login.vue
> +    <v-btn id="login-button" color="blue" class="d-inline-flex mt-5 text-none">
そうなんですね！了解です！わざわざありがとうございます！

2022-11-17 01:45 UTC, kuro48 commented
修正しました！blue-darken-3の方がfigmaの色に近かったのでそっちにしました！（勝手にごめんなさい）

2022-11-17 01:57 UTC, txxxxc approved these changes
めっちゃええ感じです！マージしちゃってください！！！

2022-11-17 05:51 UTC, merged