[add] room page
lit-kansai/dj-system-admin pull request #25
Opened 2022-11-21 04:37 UTC by kuro48

ルーム概要のUI構築完了しました！

2022-11-22 05:21 UTC, txxxxc requested changes
全体的にめっちゃ良さそう！！ホンマに助かってます🙇‍♂️
「いまさら言うんかい！」みたいな内容のレビューあるのめちゃくちゃ申し訳ないんやけど、修正してもらえるとありがたいです！
ご協力お願いします🙏

2022-11-22 05:21 UTC, txxxxc commented on src/pages/setting.vue
>      </div>
settings.vueはもう使わないので、消してもらいたいです！！
[【Git&GitHub】ファイルの削除を記録（git rmコマンド） - 未来エンジニア養成所Blog](https://phoeducation.work/entry/20210806/1628204280#:~:text=%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E5%89%8A%E9%99%A4%E3%81%97%E3%81%9F%E3%81%84%E6%99%82,%3E%E3%80%8D%E3%81%A8%E5%85%A5%E5%8A%9B%E3%81%97%E3%81%BE%E3%81%99%E3%80%82&text=%E3%80%8Cgit%20rm%E3%80%8D%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%82%92%E4%BD%BF%E3%81%86,%E3%81%AE%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%82%E6%B6%88%E3%81%88%E3%81%BE%E3%81%99%E3%80%82)

2022-11-22 05:21 UTC, txxxxc commented on src/pages/room/id.vue
> +    margin-right: 117px;
デザイン上のmargin-leftが104pxな理由って、margin-leftを104pxにしてほしいというか中央揃えにしたいって意味っぽいから一旦左右のマージンは無くしてもらえるとありがたい！(今更でごめん)
参考↓
https://lifeistech-kansai.slack.com/archives/C02NNK3V1LH/p1669094026412039

2022-11-22 05:21 UTC, txxxxc commented on src/pages/room/id.vue
> +  <div id="room-info" class="mt-16 mb-10">
ここ、marginというよりpaddingの方が適切な気がするから変えてもらえるとありがたいです🙏

2022-11-22 05:23 UTC, txxxxc commented
あとコミットの粒度に関してなんだけど、意味のある大きさで複数に分けてcommitしてもらえるとありがたいです！
この記事がめちゃくちゃわかりやすいので、見ながらやってもらえるとめちゃくちゃありがたい！！

[【初心者向け】「コミットの粒度がわからない問題」の模範解答を考えてみた - Qiita](https://qiita.com/jnchito/items/40e0c7d32fde352607be#%E5%AE%9F%E9%9A%9B%E3%81%AE%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%AD%E3%82%B0%E3%82%92%E8%A6%8B%E3%81%A6%E3%81%BF%E3%82%8B1920)

2022-11-22 07:45 UTC, txxxxc commented
あ、あとid.vueから_id.vueにファイル名変更してもらいたいです！

2022-11-23 00:27 UTC, txxxxc commented
ファイル消せてそう！！
あとはid.vueから_id.vueへのファイル名変更だけお願いします！！

2022-11-23 04:14 UTC, kuro48 commented
変更しました！

2022-11-23 14:41 UTC, txxxxc approved these changes
実装ありがとう！めっちゃ良さそうです！！
マージお願いしますー！

2022-11-24 11:10 UTC, merged