Fix/layout/default
lit-kansai/dj-system-admin pull request #39
Opened 2022-12-12 06:49 UTC by penguin4731

resolved #32

2022-12-14 08:31 UTC, txxxxc reviewed
実装ありがとう！！
いくつかコメントしました！
確認よろです！🙇‍♂️

2022-12-14 08:31 UTC, txxxxc commented on src/layouts/default.vue
> +    max-width: 1072px;
max-width: 1080pxとかでも良いかも(1072pxにしてる理由ってある？？)

2022-12-14 08:31 UTC, txxxxc commented on src/layouts/default.vue
> +    }
できればQuasarのbreakpoint使いたい！

2022-12-14 08:31 UTC, txxxxc commented on src/layouts/default.vue
>      min-height: 100vh;
Quasar側でmin-height上書きされるからmin-heightいらないかも...?
![image](https://user-images.githubusercontent.com/22112440/207543965-294438ac-e582-4593-89cb-80f54470eab0.png)

2022-12-14 08:31 UTC, txxxxc commented on src/layouts/default.vue
> +      </div>
classをq-page-containerの方に移植できたらネストが一つ少なくて済むかも！

2022-12-15 07:37 UTC, penguin4731 commented on src/layouts/default.vue
> +    }
d1d42e1c1b68d828fb5ad8994271f98ef608f76c

ここで修正

2022-12-15 07:37 UTC, penguin4731 commented on src/assets/styles/_breakpoint.scss
> +) !default;
d1d42e1c1b68d828fb5ad8994271f98ef608f76c

ここで修正

2022-12-15 07:38 UTC, penguin4731 commented on src/layouts/default.vue
>      min-height: 100vh;
929970b836ed49298adcc8ce7a27aee5bfaeecaf
こちらで修正

2022-12-15 07:38 UTC, penguin4731 commented on src/layouts/default.vue
>    }
929970b836ed49298adcc8ce7a27aee5bfaeecaf
こちらで修正

2022-12-15 07:39 UTC, penguin4731 commented on src/layouts/default.vue
> +      </div>
q-page-containerが、Drawerとかの調整をpaddingでしたりするからそこにclassを持ってきちゃうと競合しちゃうのでこのままのほうが良い気がする！

2022-12-15 07:49 UTC, penguin4731 commented on src/layouts/default.vue
> +    max-width: 1072px;
b684dbbf52ef3235a2857b76263ed31aaaf73168
理由あったけど、気持ち悪い実装やったたので↑で修正

2022-12-16 04:36 UTC, txxxxc commented on src/layouts/default.vue
> +      </div>
なるほど！！じゃあ一旦このままでお願いします！
ありがとう🙇‍♂️

2022-12-16 04:43 UTC, txxxxc reviewed
修正あざす！！一点だけ修正よろです🙇‍♂️

2022-12-16 04:43 UTC, txxxxc commented on src/layouts/default.vue
> +    @media (max-width: $breakpoint-md-max) {
`min-width`で書いたほうが後々楽なので`min-width`を使ってほしいかも🙏
[CSS MdiaQueryのmin-widthとmax-widthどちらを使う？](https://blog.tomoyukikashiro.me/ja-JP/post/media-query-min-max)

2022-12-16 06:12 UTC, txxxxc requested changes
@penguin4731 
ごめん最後に一点だけ🙇‍♂️

2022-12-16 06:12 UTC, txxxxc commented on src/layouts/default.vue
> +      margin: 0 auto;
.container {
    margin: 0 12px; // 1024以下の時

    @media (min-width: $breakpoint-md-min) {
      max-width: 1024px; // 1024以上の時にmax-widthを1024pxにする
      margin: 0 auto;
      background-color: blue;
    }

2022-12-16 06:42 UTC, txxxxc commented on src/layouts/default.vue
> +      margin: 0 auto;
これ一旦無視してもらって良きです

2022-12-16 06:43 UTC, txxxxc approved these changes

2022-12-19 05:57 UTC, merged